description: |
  ### Document Name - SHARR-AFSBP_1.0.0_DynamoDB.2

  ## What does this document do?
  This document restricts cross-account access to a bucket in the local account.

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.

  ## Output Parameters
  * Remediation.Output

  ## Documentation Links
  * [AFSBP v1.0.0 DynamoDB.2](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#dynamodb-2-remediation)

schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
outputs:
  - ParseInput.AffectedObject
  - Remediation.Output
parameters:
  Finding:
    type: StringMap
    description: The input from the Orchestrator Step function for the DynamoDB.2 finding
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'
  RemediationRoleName:
    type: String
    default: "SO0111-DynamoDBPITRRole"
    allowedPattern: '^[\w+=,.@-]+'

mainSteps:
  -
    name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: '^arn:(?:aws|aws-cn|aws-us-gov):dynamodb:::([A-Za-z0-9.-]{3,63})$'
        expected_control_id: [ 'DynamoDB.2' ]
      Runtime: python3.8
      Handler: parse_event
      Script: |-
        %%SCRIPT=common/parse_input.py%%
  -
    name: Remediation
    action: 'aws:executeAutomation'
    inputs:
      DocumentName: SHARR-EnableDynamoDB_PITR
      RuntimeParameters:
        TableArn: '{{ParseInput.AffectedObject}}'
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/{{RemediationRoleName}}'

  -
    name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Set point-in-time recovery on Table {{ParseInput.TableName}}'
        UpdatedBy: 'SHARR-AFSBP_1.0.0_DynamoDB.2'
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true
